#Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.

tab = int(input('Digite um numero para ver sua Tabuada '))
print('='*10)
print(f'{tab} x 1 = {tab*1} ')
print(f'{tab} x 2 = {tab*2} ')
print(f'{tab} x 3 = {tab*3} ')
print(f'{tab} x 4 = {tab*4} ')
print(f'{tab} x 5 = {tab*5} ')
print(f'{tab} x 6 = {tab*6} ')
print(f'{tab} x 7 = {tab*7} ')
print(f'{tab} x 8 = {tab*8} ')
print(f'{tab} x 9 = {tab*9} ')
print(f'{tab} x 10 = {tab*10} ')
print('='*10)